import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import SideBar from "@/components/SideBar";
import QueryProvider from "../providers/QueryProvider";
import AuthNav from "@/components/AuthNav";
import SearchBar from "@/components/SearchBar";

export const metadata: Metadata = {
  title: "Spartify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-charcoal text-white">
        <header className="fixed top-0 left-0 w-full h-16 bg-charcoal">
          <AuthNav />
        </header>

        <aside className="fixed top-16 left-0 w-[240px] h-[calc(100vh-4rem)]">
          <SideBar />
        </aside>

        <div className="ml-[240px] mt-16 h-[calc(100vh-4rem)] overflow-y-auto">
          <main className="bg-gunmetal m-4 border border-transparent rounded-lg">
            <QueryProvider>{children}</QueryProvider>
          </main>
          <footer className="bg-charcoal font-thin p-2 relative">
            <p>©2025 project-Spartify</p>
            <p>문정빈, 박나현, 송제우, 오영진, 이수민</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
